name: "Backend Infrastructure Deployment"

on:
  push:
    branches:
    - master
    paths:
    - Portfolio_website/infrastructure/**
  pull_request:
    branches:
    - master
    paths: 
    - Portfolio_website/infrastructure/**

env:  
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}  
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  
  TF_STATE_BUCKET_NAME: ${{ secrets.AWS_TF_STATE_BUCKET_NAME }}
  AWS_REGION: eu-west-2

jobs:
  build:
    name: Deploy Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform init
        id: init
        run: terraform init
        working-directory: Portfolio_website/infrastructure/

      - name: Terraform Plan
        id: plan
        run: terraform plan
        working-directory: Portfolio_website/infrastructure/

      - name: Terraform Apply
        id: apply
        run: terraform apply --auto-approve
        working-directory: Portfolio_website/infrastructure/

      - name: Conditional Terraform Destroy
        id: conditional_destroy
        run: |
          if [[ ${{ steps.apply.outcome }} == "failure" ]]; then
            terraform destroy --auto-approve
          fi
        working-directory: Portfolio_website/infrastructure/

      - name: Set Backend Deployment Status
        id: backend_status
        run: |
          if [[ ${{ steps.apply.outcome }} == "success" ]]; then
            echo "Backend Deployment Status: success"
          else
            echo "Backend Deployment Status: failure"
          fi