name: Deploy Frontend to S3 and Cloudfront Cache Invalidation

on:
  workflow_run:
    workflows: ["Backend Infrastructure Deployment"]
    types:
      - completed

  push:
    branches:
      - master
    paths:
      - Portfolio_website/src/**
  pull_request:
    branches:
      - master
    paths:
      - Portfolio_website/src/**

jobs:
  deploy_and_invalidate_cf_cache:
    runs-on: ubuntu-latest

    steps:
      - name: Check Backend Deployment Status
        id: check_backend
        run: echo "Backend Deployment Completed"

      - name: Set CloudFront Distribution ID
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        run: echo "CLOUDFRONT_DISTRIBUTION_ID=${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}" >> $GITHUB_ENV

      - name: Checkout code
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Upload src to S3
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        run: |
          aws s3 cp Portfolio_website/src/ s3://www.yasingole.co.uk/ --recursive

      - name: Get CloudFront Distribution ID
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        id: cloudfront
        run: |
          cloudfrontDomain="yasingole.co.uk"
          cloudfrontId=$(aws cloudfront list-distributions --query "DistributionList.Items[?DomainName=='$cloudfrontDomain'].Id" --output text)
          echo "::set-output name=distribution_id::$cloudfrontId"

      - name: Create CloudFront Invalidation
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        run: |
          distributionId="${{ steps.cloudfront.outputs.distribution_id }}"
          aws configure set preview.cloudfront true
          aws cloudfront create-invalidation --distribution-id $distributionId --paths '/*'
