name: Deploy Frontend to S3 and Cloudfront Cache Invalidation

on:
  push:
    branches:
      - master
    paths:
      - Portfolio_website/**

jobs:
  frontend_deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up AWS CLI for Frontend
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Upload src to S3
        run: |
          aws s3 sync Portfolio_website/src/ s3://www.yasingole.co.uk/ --delete 


      - name: TEST_Check_Backend_Status
        id: backend_status
        run: |
          # Check if the backend is present by making an HTTP request to your domain
          response_code=$(curl -s -o /dev/null -w "%{http_code}" https://yasingole.co.uk)
          if [[ $response_code != "200" ]]; then
            echo "Backend is not present or the domain is not accessible."
          else
            echo "Backend is present and accessible."
          fi
